name: Download slayer Securely

on:
  schedule:
    - cron: '*/10 8,20 * * *'  # 每天8点、20点运行
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Secure slayer Download
      run: |
        echo "::add-mask::$SLAYER_URL"
        
        MAX_RETRIES=10
        RETRY_DELAY=5
        COUNT=0

        while [ $COUNT -lt $MAX_RETRIES ]; do
          wget --tries=1 --wait=5 --quiet --output-document=slayer "$SLAYER_URL" && break
          COUNT=$((COUNT+1))
          echo "Download failed... retrying ($COUNT/$MAX_RETRIES) in $RETRY_DELAY seconds"
          sleep $RETRY_DELAY
        done

        if [ $COUNT -eq $MAX_RETRIES ]; then
          echo "Download failed after $MAX_RETRIES attempts"
          exit 1
        fi
      env:
        SLAYER_URL: ${{ secrets.SLAYER_URL }}

    - name: Check if slayer exists
      run: |
        if [ -f slayer ]; then echo "File slayer downloaded successfully"; else echo "File slayer not downloaded"; fi

    - name: Add and commit changes if needed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add slayer 
        git status
        git commit -m "Update slayer" || echo "slayer no changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
