name: Download Anya.txt Securely

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时运行一次
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Secure Download
      run: |
        echo "::add-mask::$ANYA_URL"
        wget --quiet --output-document=anya "$ANYA_URL"
      env:
        ANYA_URL: ${{ secrets.ANYA_URL }}

    - name: Check if anya exists
      run: |
        if [ -f anya ]; then echo "File downloaded successfully"; else echo "File not downloaded"; fi

    - name: Add and commit changes if needed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add anya
        git status
        git commit -m "Update anya" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
